
version: '3.8'
services:
  db:
    image: arm64v8/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    networks:
      - app-network
    ports:
      - "${DB_EXTERNAL_PORT}:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./roobet.sql:/docker-entrypoint-initdb.d/roobet.sql

  grafana:
    image: grafana/grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    networks:
      - app-network

  node:
    build: .
    depends_on:
      - db
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    networks:
      - app-network
    environment:
      - PMA_HOST=db
      - "PMA_ABSOLUTE_URI=${PHPMYADMIN_URL}"

networks:
  app-network:
    driver: bridge
  