# neni otestovano
version: '3.8'
services:
  db:
    image: arm64v8/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:3306"
    networks:
      - app-network
    volumes:
      - ./roobet.sql:/docker-entrypoint-initdb.d/roobet.sql

  grafana:
    image: grafana/grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    networks:
      - app-network

  node:
    build: .
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
