{
 "title": "Roobet Data",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Casino profit",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT SUM(-profit) FROM roobet.bet "
    }
   ]
  },
  {
   "title": "Total bet amount",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT SUM(betAmount) FROM roobet.bet LIMIT 50 "
    }
   ]
  },
  {
   "title": "Max Win",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT MAX(profit) FROM roobet.bet LIMIT 50 "
    }
   ]
  },
  {
   "title": "Max Lost",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT MIN(profit) FROM roobet.bet LIMIT 50 "
    }
   ]
  },
  {
   "title": "WebSocket status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT CASE WHEN COUNT(*) > 0 THEN '✅' ELSE '⚠️' END AS result\r\nFROM roobet.bet\r\nWHERE createdAt >= DATE_SUB(NOW(), INTERVAL 1 MINUTE);\r\n"
    }
   ]
  },
  {
   "title": "Total users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT COUNT(id) FROM roobet.users LIMIT 50 "
    }
   ]
  },
  {
   "title": "Active users past 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT COUNT(DISTINCT userId) FROM `bet` WHERE createdAt >= DATE_SUB(NOW(), INTERVAL 24 HOUR);"
    }
   ]
  },
  {
   "title": "Active users past 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT COUNT(DISTINCT userId) FROM `bet` WHERE createdAt >= DATE_SUB(NOW(), INTERVAL 24 HOUR);"
    }
   ]
  },
  {
   "title": "Active users past month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT COUNT(DISTINCT userId) FROM `bet` WHERE createdAt >= DATE_SUB(NOW(), INTERVAL 1 MONTH);"
    }
   ]
  },
  {
   "title": "Most popular game by the number of unique players",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT IFNULL(gameNameDisplay, gameName) as Game\r\nFROM bet\r\nGROUP BY gameNameDisplay\r\nORDER BY COUNT(DISTINCT userId) DESC\r\nLIMIT 1;\r\n"
    },
    {
     "rawSql": "SELECT COUNT(DISTINCT userId) as Players\r\nFROM bet\r\nGROUP BY gameNameDisplay\r\nORDER BY Players DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "Most popular game by the number of bets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT IFNULL(gameNameDisplay, gameName) as Game\r\nFROM bet\r\nGROUP BY gameNameDisplay\r\nORDER BY COUNT(*) DESC\r\nLIMIT 1;\r\n"
    },
    {
     "rawSql": "SELECT COUNT(*) AS numBets\r\nFROM bet\r\nGROUP BY gameNameDisplay\r\nORDER BY numBets DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "Most popular game by the number of unique players",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT IFNULL(gameNameDisplay, gameName) AS Game\r\nFROM bet\r\nGROUP BY gameNameDisplay\r\nORDER BY SUM(payoutValue) DESC\r\nLIMIT 1;"
    },
    {
     "rawSql": "SELECT SUM(payoutValue) AS Payout\r\nFROM bet\r\nGROUP BY gameNameDisplay\r\nORDER BY Payout DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "Profit %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT (COUNT(CASE WHEN profit > 0 THEN 1 END) / COUNT(*)) * 100 AS profitPercentage\r\nFROM bet;\r\n"
    }
   ]
  },
  {
   "title": "Highest bet",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT MAX(betAmount) FROM roobet.bet LIMIT 50 "
    }
   ]
  },
  {
   "title": "Average bet amount",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT AVG(betAmount) FROM roobet.bet LIMIT 50 "
    }
   ]
  },
  {
   "title": "Average profit of all bets",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT AVG(profit) FROM roobet.bet LIMIT 50 "
    }
   ]
  },
  {
   "title": "10 Most popular games ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT IFNULL(gameNameDisplay, gameName), COUNT(*) as numBets FROM bet GROUP BY gameNameDisplay ORDER BY numBets DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "10 Least popular games ",
   "type": "piechart",
   "description": "there is little data in the database, over time this graph will correct itself",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT IFNULL(gameNameDisplay, gameName), COUNT(*) as numBets FROM bet GROUP BY gameNameDisplay ORDER BY numBets ASC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Most profitable games to play (AVG profit)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT IFNULL(gameNameDisplay, gameName) as gameName, AVG(profit) AS avgProfit FROM bet WHERE profit IS NOT NULL GROUP BY gameNameDisplay ORDER BY avgProfit DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Least profitable games to play (AVG profit)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT IFNULL(gameNameDisplay, gameName) as gameName, AVG(profit) AS avgProfit FROM bet WHERE profit IS NOT NULL GROUP BY gameNameDisplay ORDER BY avgProfit ASC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Most profitable games to play (SUM profit)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT IFNULL(gameNameDisplay, gameName) as gameName, SUM(profit) AS avgProfit FROM bet WHERE profit IS NOT NULL GROUP BY gameNameDisplay ORDER BY avgProfit DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Least profitable games to play (SUM profit)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT IFNULL(gameNameDisplay, gameName) as gameName, SUM(profit) AS avgProfit FROM bet WHERE profit IS NOT NULL GROUP BY gameNameDisplay ORDER BY avgProfit ASC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Users who wagered the most money (Top 10)",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT IFNULL(u.name, 'anonymous') AS username, SUM(b.betAmount) AS totalBetAmount, SUM(b.profit) AS totalProfit\r\nFROM bet b\r\nLEFT JOIN users u ON b.userId = u.id\r\nWHERE b.betAmount IS NOT NULL\r\nGROUP BY b.userId\r\nORDER BY totalBetAmount DESC\r\nLIMIT 10;\r\n"
    }
   ]
  },
  {
   "title": "Users with the highest total profit (Top 10)",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT IFNULL(u.name, 'anonymous') AS username, SUM(b.betAmount) AS totalBetAmount, SUM(b.profit) AS totalProfit\r\nFROM bet b\r\nLEFT JOIN users u ON b.userId = u.id\r\nWHERE b.profit IS NOT NULL\r\nGROUP BY b.userId\r\nORDER BY totalProfit DESC\r\nLIMIT 10;\r\n"
    }
   ]
  },
  {
   "title": "Users with the lowest total profit (Top 10)",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT IFNULL(u.name, 'anonymous') AS username, SUM(b.betAmount) AS totalBetAmount, SUM(b.profit) AS totalProfit\r\nFROM bet b\r\nLEFT JOIN users u ON b.userId = u.id\r\nWHERE b.profit IS NOT NULL\r\nGROUP BY b.userId\r\nORDER BY totalProfit ASC\r\nLIMIT 10;\r\n"
    }
   ]
  },
  {
   "title": "Users who made the most bets (Top 10)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT IFNULL(u.name, 'anonymous') AS username, SUM(b.betAmount) AS totalBetAmount, COUNT(*) AS numBets, SUM(b.profit) AS totalProfit, MAX(b.profit) AS maxWin, MIN(b.profit) AS maxLose, AVG(b.profit) AS avgProfit, MAX(b.betAmount) AS maxBetAmount, MIN(b.betAmount) AS minBetAmount, AVG(b.betAmount) AS avgBetAmount\r\nFROM bet b\r\nLEFT JOIN users u ON b.userId = u.id\r\nGROUP BY b.userId\r\nORDER BY numBets DESC\r\nLIMIT 10;"
    }
   ]
  }
 ]
}