{
 "title": "Specific Game",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "game",
    "label": "Game",
    "query": "SELECT DISTINCT IFNULL(gameNameDisplay, gameName) from roobet.bet"
   },
   {
    "name": "timerange",
    "label": "Timerange",
    "query": "5m,15m,30m,1h,3h,6h,12h,24h,2d,7d,30d,90d,6mo,1y"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of bets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT COUNT(*) FROM roobet.bet WHERE IFNULL(gameNameDisplay, gameName) = '$game' AND $__timeFilter(createdAt);"
    }
   ]
  },
  {
   "title": "Sum of profit from this game",
   "type": "stat",
   "gridPos": { "h": 10, "w": 10, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT SUM(profit) FROM roobet.bet WHERE IFNULL(gameNameDisplay, gameName) = '$game' AND $__timeFilter(createdAt);"
    }
   ]
  },
  {
   "title": "Avg bet profit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT AVG(profit) FROM roobet.bet WHERE IFNULL(gameNameDisplay, gameName) = '$game' AND $__timeFilter(createdAt);"
    }
   ]
  },
  {
   "title": "Number of players",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT COUNT(DISTINCT userID) FROM roobet.bet WHERE IFNULL(gameNameDisplay, gameName) = '$game' AND $__timeFilter(createdAt);"
    }
   ]
  },
  {
   "title": "Max win / lose",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT MAX(profit) as Win, MIN(profit) as Lose FROM roobet.bet WHERE IFNULL(gameNameDisplay, gameName) = '$game'  AND $__timeFilter(createdAt);"
    }
   ]
  },
  { "title": "Time series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Casino profit from game",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroupAlias(createdAt,'$timerange'), \r\n  SUM(-profit) AS 'Casino Profit'\r\nFROM bet\r\nWHERE $__timeFilter(createdAt) AND IFNULL(gameNameDisplay, gameName) = '$game'\r\nGROUP BY 1\r\nORDER BY $__timeGroup(createdAt,'$timerange')\r\n"
    }
   ]
  },
  {
   "title": "Total bet amount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroupAlias(createdAt,'$timerange'), \r\n  SUM(betAmount) AS 'Total Bet Amount'\r\nFROM bet\r\nWHERE $__timeFilter(createdAt) AND IFNULL(gameNameDisplay, gameName) = '$game'\r\nGROUP BY 1\r\nORDER BY $__timeGroup(createdAt,'$timerange')\r\n"
    }
   ]
  },
  {
   "title": "Number of bets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroupAlias(createdAt,'$timerange'), \r\n  COUNT(betId) AS 'Total Bets'\r\nFROM bet\r\nWHERE $__timeFilter(createdAt) AND IFNULL(gameNameDisplay, gameName) = '$game'\r\nGROUP BY 1\r\nORDER BY $__timeGroup(createdAt,'$timerange')\r\n"
    }
   ]
  },
  {
   "title": "Number of players",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroupAlias(createdAt,'$timerange'), \r\n  COUNT(DISTINCT userId) AS 'Distinct Players'\r\nFROM bet\r\nWHERE IFNULL(gameNameDisplay, gameName) = '$game'\r\nAND $__timeFilter(createdAt)\r\nGROUP BY 1\r\nORDER BY $__timeGroup(createdAt,'$timerange')\r\n"
    }
   ]
  },
  {
   "title": "Max Win",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroupAlias(createdAt,'$timerange'), \r\n  MAX(profit) AS 'Max Win'\r\nFROM bet\r\nWHERE $__timeFilter(createdAt) AND IFNULL(gameNameDisplay, gameName) = '$game'\r\nGROUP BY 1\r\nORDER BY $__timeGroup(createdAt,'$timerange')\r\n"
    }
   ]
  },
  {
   "title": "Percentage of profitable bets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroupAlias(createdAt,'$timerange'),\r\n  (COUNT(CASE WHEN profit > 0 THEN 1 END) / COUNT(*)) * 100 AS 'Profit Percentage'\r\nFROM bet\r\nWHERE $__timeFilter(createdAt) AND IFNULL(gameNameDisplay, gameName) = '$game'\r\nGROUP BY 1\r\nORDER BY $__timeGroup(createdAt,'$timerange')\r\n"
    }
   ]
  },
  {
   "title": "Average bet amount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroupAlias(createdAt,'$timerange'), \r\n  AVG(betAmount) AS 'Avg Bet Amount'\r\nFROM bet\r\nWHERE $__timeFilter(createdAt) AND IFNULL(gameNameDisplay, gameName) = '$game'\r\nGROUP BY 1\r\nORDER BY $__timeGroup(createdAt,'$timerange')\r\n"
    }
   ]
  },
  {
   "title": "Max Lost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroupAlias(createdAt,'$timerange'), \r\n  MIN(profit) AS 'Min Profit'\r\nFROM bet\r\nWHERE $__timeFilter(createdAt) AND IFNULL(gameNameDisplay, gameName) = '$game'\r\nGROUP BY 1\r\nORDER BY $__timeGroup(createdAt,'$timerange')\r\n"
    }
   ]
  },
  {
   "title": "Users",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Users who wagered the most money",
     "type": "table",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "rawSql": "SELECT IFNULL(u.name, 'anonymous') AS username, SUM(b.betAmount) AS totalBetAmount, SUM(b.profit) AS totalProfit\r\nFROM bet b\r\nLEFT JOIN users u ON b.userId = u.id\r\nWHERE b.betAmount IS NOT NULL AND $__timeFilter(createdAt) AND IFNULL(gameNameDisplay, gameName) = '$game'\r\nGROUP BY b.userId\r\nORDER BY totalBetAmount DESC\r\nLIMIT 300;\r\n"
      }
     ]
    },
    {
     "title": "Users with the highest total profit",
     "type": "table",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "rawSql": "SELECT IFNULL(u.name, 'anonymous') AS username, SUM(b.betAmount) AS totalBetAmount, SUM(b.profit) AS totalProfit\r\nFROM bet b\r\nLEFT JOIN users u ON b.userId = u.id\r\nWHERE b.profit IS NOT NULL AND $__timeFilter(createdAt) AND IFNULL(gameNameDisplay, gameName) = '$game'\r\nGROUP BY b.userId\r\nORDER BY totalProfit DESC\r\nLIMIT 300;\r\n"
      }
     ]
    },
    {
     "title": "Users with the lowest total profit",
     "type": "table",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "rawSql": "SELECT IFNULL(u.name, 'anonymous') AS username, SUM(b.betAmount) AS totalBetAmount, SUM(b.profit) AS totalProfit\r\nFROM bet b\r\nLEFT JOIN users u ON b.userId = u.id\r\nWHERE b.profit IS NOT NULL AND $__timeFilter(createdAt) AND IFNULL(gameNameDisplay, gameName) = '$game'\r\nGROUP BY b.userId\r\nORDER BY totalProfit ASC\r\nLIMIT 300;\r\n"
      }
     ]
    },
    {
     "title": "Users who made the most bets",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT IFNULL(u.name, 'anonymous') AS username, COUNT(*) AS numBets, SUM(b.betAmount) AS totalBetAmount, SUM(b.profit) AS totalProfit, MAX(b.profit) AS maxWin, MIN(b.profit) AS maxLose, AVG(b.profit) AS avgProfit, MAX(b.betAmount) AS maxBetAmount, MIN(b.betAmount) AS minBetAmount, AVG(b.betAmount) AS avgBetAmount\r\nFROM bet b\r\nLEFT JOIN users u ON b.userId = u.id\r\nWHERE $__timeFilter(b.createdAt) AND IFNULL(gameNameDisplay, gameName) = '$game'\r\nGROUP BY b.userId\r\nORDER BY numBets DESC\r\nLIMIT 300;"
      }
     ]
    }
   ]
  }
 ]
}