{
 "title": "Roobet Data v2",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "timerange",
    "label": "Timerange",
    "query": "5m,15m,30m,1h,3h,6h,12h,24h,2d,7d,30d,90d,6mo,1y"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Casino profit",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT SUM(-profit) FROM roobet.bet WHERE $__timeFilter(createdAt);"
    }
   ]
  },
  {
   "title": "Total bet amount",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT SUM(betAmount) FROM roobet.bet WHERE $__timeFilter(createdAt)"
    }
   ]
  },
  {
   "title": "Max Win",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT MAX(profit) FROM roobet.bet WHERE $__timeFilter(createdAt);"
    }
   ]
  },
  {
   "title": "Max Lost",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT MIN(profit) FROM roobet.bet WHERE $__timeFilter(createdAt);"
    }
   ]
  },
  {
   "title": "Total users",
   "type": "stat",
   "description": "does not depend on the time filter",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT COUNT(id) FROM roobet.users LIMIT 50 "
    }
   ]
  },
  {
   "title": "Active users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroupAlias(createdAt,'$timerange'), \r\n  COUNT(DISTINCT userId) AS 'Active Users'\r\nFROM bet\r\nWHERE $__timeFilter(createdAt)\r\nGROUP BY 1\r\nORDER BY $__timeGroup(createdAt,'$timerange')\r\n"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "stat",
   "description": "active betting users in the time filter",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT COUNT(DISTINCT userId) FROM `bet` WHERE $__timeFilter(createdAt)"
    }
   ]
  },
  {
   "title": "WebSocket ",
   "type": "stat",
   "description": "status of data connector",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT CASE WHEN COUNT(*) > 0 THEN '✅' ELSE '⚠️' END AS result\r\nFROM roobet.bet\r\nWHERE createdAt >= DATE_SUB(NOW(), INTERVAL 1 MINUTE);\r\n"
    }
   ]
  },
  {
   "title": "Most popular game by the number of unique players",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT IFNULL(gameNameDisplay, gameName) as Game\r\nFROM bet\r\nWHERE $__timeFilter(createdAt)\r\nGROUP BY gameNameDisplay\r\nORDER BY COUNT(DISTINCT userId) DESC\r\nLIMIT 1;\r\n\r\n"
    },
    {
     "rawSql": "SELECT COUNT(DISTINCT userId) as Players\r\nFROM bet\r\nWHERE $__timeFilter(createdAt)\r\nGROUP BY gameNameDisplay\r\nORDER BY Players DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "Most popular game by the number of bets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT IFNULL(gameNameDisplay, gameName) as Game\r\nFROM bet\r\nWHERE $__timeFilter(createdAt)\r\nGROUP BY gameNameDisplay\r\nORDER BY COUNT(*) DESC\r\nLIMIT 1;\r\n"
    },
    {
     "rawSql": "SELECT COUNT(*) AS numBets\r\nFROM bet\r\nWHERE $__timeFilter(createdAt)\r\nGROUP BY gameNameDisplay\r\nORDER BY numBets DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "Most popular game by the highest payout",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT IFNULL(gameNameDisplay, gameName) AS Game\r\nFROM bet\r\nWHERE $__timeFilter(createdAt)\r\nGROUP BY gameNameDisplay\r\nORDER BY SUM(profit) DESC\r\nLIMIT 1;\r\n"
    },
    {
     "rawSql": "SELECT SUM(profit) AS Payout\r\nFROM bet\r\nWHERE $__timeFilter(createdAt)\r\nGROUP BY gameNameDisplay\r\nORDER BY Payout DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "Profit %",
   "type": "gauge",
   "description": "how many % of all bets is profitable",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT (COUNT(CASE WHEN profit > 0 THEN 1 END) / COUNT(*)) * 100 AS profitPercentage\r\nFROM bet\r\nWHERE $__timeFilter(createdAt);\r\n"
    }
   ]
  },
  {
   "title": "Highest bet",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT MAX(betAmount) FROM roobet.bet WHERE $__timeFilter(createdAt);"
    }
   ]
  },
  {
   "title": "Average bet amount",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT AVG(betAmount) FROM roobet.bet WHERE $__timeFilter(createdAt);"
    }
   ]
  },
  {
   "title": "Average profit of all bets",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "roobet",
     "rawSql": "SELECT AVG(profit) FROM roobet.bet WHERE $__timeFilter(createdAt);"
    }
   ]
  },
  {
   "title": "10 Most popular games ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT IFNULL(gameNameDisplay, gameName), COUNT(*) as numBets FROM bet WHERE $__timeFilter(createdAt) GROUP BY gameNameDisplay ORDER BY numBets DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Least popular games ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  IFNULL(b.gameNameDisplay, b.gameName) AS game, \r\n  COUNT(b.betId) AS numBets\r\nFROM bet AS b\r\nWHERE $__timeFilter(b.createdAt)\r\nGROUP BY game\r\nHAVING COUNT(b.betId) =\r\n(\r\n  SELECT \r\n    COUNT(betId)\r\n  FROM bet\r\n  WHERE $__timeFilter(createdAt)\r\n  GROUP BY IFNULL(gameNameDisplay, gameName)\r\n  ORDER BY COUNT(betId) ASC\r\n  LIMIT 1\r\n);\r\n"
    }
   ]
  },
  {
   "title": "Most profitable games to play (AVG profit)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT IFNULL(gameNameDisplay, gameName) as gameName, AVG(profit) AS avgProfit FROM bet WHERE profit IS NOT NULL AND $__timeFilter(createdAt) GROUP BY gameNameDisplay ORDER BY avgProfit DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Least profitable games to play (AVG profit)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT IFNULL(gameNameDisplay, gameName) as gameName, AVG(profit) AS avgProfit FROM bet WHERE profit IS NOT NULL AND $__timeFilter(createdAt) GROUP BY gameNameDisplay ORDER BY avgProfit ASC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Most profitable games to play (SUM profit)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT IFNULL(gameNameDisplay, gameName) as gameName, SUM(profit) AS avgProfit FROM bet WHERE profit IS NOT NULL AND $__timeFilter(createdAt) GROUP BY gameNameDisplay ORDER BY avgProfit DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Least profitable games to play (SUM profit)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT IFNULL(gameNameDisplay, gameName) as gameName, SUM(profit) AS avgProfit FROM bet WHERE profit IS NOT NULL AND $__timeFilter(createdAt) GROUP BY gameNameDisplay ORDER BY avgProfit ASC LIMIT 10;"
    }
   ]
  },
  { "title": "Time series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Casino profit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroupAlias(createdAt,'$timerange'), \r\n  SUM(-profit) AS 'Casino Profit'\r\nFROM bet\r\nWHERE $__timeFilter(createdAt)\r\nGROUP BY 1\r\nORDER BY $__timeGroup(createdAt,'$timerange')\r\n"
    }
   ]
  },
  {
   "title": "Total bet amount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroupAlias(createdAt,'$timerange'), \r\n  SUM(betAmount) AS 'Total Bet Amount'\r\nFROM bet\r\nWHERE $__timeFilter(createdAt)\r\nGROUP BY 1\r\nORDER BY $__timeGroup(createdAt,'$timerange')\r\n"
    }
   ]
  },
  {
   "title": "Number of bets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroupAlias(createdAt,'$timerange'), \r\n  COUNT(betId) AS 'Total Bets'\r\nFROM bet\r\nWHERE $__timeFilter(createdAt)\r\nGROUP BY 1\r\nORDER BY $__timeGroup(createdAt,'$timerange')\r\n"
    }
   ]
  },
  {
   "title": "Percentage of profitable bets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroupAlias(createdAt,'$timerange'),\r\n  (COUNT(CASE WHEN profit > 0 THEN 1 END) / COUNT(*)) * 100 AS 'Profit Percentage'\r\nFROM bet\r\nWHERE $__timeFilter(createdAt)\r\nGROUP BY 1\r\nORDER BY $__timeGroup(createdAt,'$timerange')\r\n"
    }
   ]
  },
  {
   "title": "Max Win",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroupAlias(createdAt,'$timerange'), \r\n  MAX(profit) AS 'Max Win'\r\nFROM bet\r\nWHERE $__timeFilter(createdAt)\r\nGROUP BY 1\r\nORDER BY $__timeGroup(createdAt,'$timerange')\r\n"
    }
   ]
  },
  {
   "title": "Max Lost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroupAlias(createdAt,'$timerange'), \r\n  MIN(profit) AS 'Min Profit'\r\nFROM bet\r\nWHERE $__timeFilter(createdAt)\r\nGROUP BY 1\r\nORDER BY $__timeGroup(createdAt,'$timerange')\r\n"
    }
   ]
  },
  {
   "title": "Unique games played",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroupAlias(createdAt,'$timerange'), \r\n  COUNT(DISTINCT IFNULL(gameNameDisplay, gameName)) AS 'Unique Games'\r\nFROM bet\r\nWHERE $__timeFilter(createdAt)\r\nGROUP BY 1\r\nORDER BY $__timeGroup(createdAt,'$timerange')\r\n"
    }
   ]
  },
  {
   "title": "Average bet amount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroupAlias(createdAt,'$timerange'), \r\n  AVG(betAmount) AS 'Avg Bet Amount'\r\nFROM bet\r\nWHERE $__timeFilter(createdAt)\r\nGROUP BY 1\r\nORDER BY $__timeGroup(createdAt,'$timerange')\r\n"
    }
   ]
  },
  {
   "title": "Users",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 },
   "collapsed": true,
   "panels": [
    {
     "title": "Users who wagered the most money",
     "type": "table",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "rawSql": "SELECT IFNULL(u.name, 'anonymous') AS username, SUM(b.betAmount) AS totalBetAmount, SUM(b.profit) AS totalProfit\r\nFROM bet b\r\nLEFT JOIN users u ON b.userId = u.id\r\nWHERE b.betAmount IS NOT NULL AND $__timeFilter(createdAt)\r\nGROUP BY b.userId\r\nORDER BY totalBetAmount DESC\r\nLIMIT 300;\r\n"
      }
     ]
    },
    {
     "title": "Users with the highest total profit",
     "type": "table",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "rawSql": "SELECT IFNULL(u.name, 'anonymous') AS username, SUM(b.betAmount) AS totalBetAmount, SUM(b.profit) AS totalProfit\r\nFROM bet b\r\nLEFT JOIN users u ON b.userId = u.id\r\nWHERE b.profit IS NOT NULL AND $__timeFilter(createdAt)\r\nGROUP BY b.userId\r\nORDER BY totalProfit DESC\r\nLIMIT 300;\r\n"
      }
     ]
    },
    {
     "title": "Users with the lowest total profit",
     "type": "table",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "rawSql": "SELECT IFNULL(u.name, 'anonymous') AS username, SUM(b.betAmount) AS totalBetAmount, SUM(b.profit) AS totalProfit\r\nFROM bet b\r\nLEFT JOIN users u ON b.userId = u.id\r\nWHERE b.profit IS NOT NULL AND $__timeFilter(createdAt)\r\nGROUP BY b.userId\r\nORDER BY totalProfit ASC\r\nLIMIT 300;\r\n"
      }
     ]
    },
    {
     "title": "Users who made the most bets",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT IFNULL(u.name, 'anonymous') AS username, COUNT(*) AS numBets, SUM(b.betAmount) AS totalBetAmount, SUM(b.profit) AS totalProfit, MAX(b.profit) AS maxWin, MIN(b.profit) AS maxLose, AVG(b.profit) AS avgProfit, MAX(b.betAmount) AS maxBetAmount, MIN(b.betAmount) AS minBetAmount, AVG(b.betAmount) AS avgBetAmount\r\nFROM bet b\r\nLEFT JOIN users u ON b.userId = u.id\r\nWHERE $__timeFilter(b.createdAt)\r\nGROUP BY b.userId\r\nORDER BY numBets DESC\r\nLIMIT 300;"
      }
     ]
    }
   ]
  }
 ]
}